name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    - name: Build Documentation
      run: |
        cd docs
        make html

    - name: Upload Documentation Artifact
      uses: actions/upload-artifact@v3
      with:
        name: docs-html
        path: docs/_build/html

